sensor:

  # Header Outdoor Temperate
  - platform: homeassistant
    entity_id: sensor.vyshneve_vulitsia_temperature
    id: office_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(id(office_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.vyshneve_vulitsia_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(x)', '(int)round(id(outdoor_temperature).state)' ]

binary_sensor:
  - platform: homeassistant
    id: corridor_light_state
    entity_id: light.corridor_light
    publish_initial_state: true
#    internal: true
    on_state:
      - lvgl.widget.update:
          id: battery_rack_light
          state:
            checked: !lambda 'return x;'
