sensor:

  # Header Outdoor Temperate
  - platform: homeassistant
    entity_id: sensor.vyshneve_vulitsia_temperature
    id: office_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(id(office_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.vyshneve_vulitsia_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(x)', '(int)round(id(outdoor_temperature).state)' ]


binary_sensor:
  # Office Aircon
  - platform: homeassistant
    id: office_air_conditioner
    entity_id: switch.office_air_conditioner
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_aircon_button
          state:
            checked: !lambda return x;

  # Corridor Lights
  - platform: homeassistant
    id: office_storage_lights
    entity_id: light.corridor_light
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: storage_lights_button
          state:
            checked: !lambda return x;

  # Network Rack
  - platform: homeassistant
    id: network_rack
    entity_id: light.corridor_light
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: network_rack_button
          state:
            checked: !lambda return x;
